const CSS = [
  ':root{--bg:#0c0e15;--panel:#141824;--panel2:#191e2c;--text:#f4f4f7;--muted:#969dad;--line:#2a3040;--violet:#8276e8;--gold:#e7c886;--green:#79d6a3;--red:#ff8e92}',
  '*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--text);font:14px/1.45 Inter,system-ui,-apple-system,Segoe UI,sans-serif}',
  'a{color:#b8afff}.wrap{max-width:1500px;margin:auto;padding:26px}.top{display:flex;justify-content:space-between;align-items:flex-start;gap:18px}',
  '.brand h1{margin:0;font-size:32px;letter-spacing:-.045em}.brand p{margin:6px 0;color:var(--muted)}.controls{display:flex;gap:8px;align-items:center}',
  '.market{background:#0f121b;border:1px solid var(--line);color:var(--text);padding:11px;border-radius:10px}.btn{border:0;background:var(--violet);color:#fff;font-weight:750;border-radius:10px;padding:12px 17px;cursor:pointer}.btn:disabled{opacity:.5}',
  '.notice,.panel,.stat,.card{border:1px solid var(--line);background:var(--panel);border-radius:14px}.notice{margin:18px 0;padding:12px 14px;color:var(--gold);border-color:#5a4d2f;background:#17150f}.error{color:var(--red);border-color:#66383b;background:#1a1114}',
  '.grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:12px}.stat{padding:15px}.stat .k{font-size:11px;color:var(--muted);text-transform:uppercase}.stat .v{font-size:26px;font-weight:800;margin-top:4px}',
  '.panel{padding:17px;margin-top:14px}.panel h2{margin:0 0 12px;font-size:15px}.table{width:100%;border-collapse:collapse}.table th,.table td{padding:9px 8px;border-bottom:1px solid var(--line);text-align:left;vertical-align:top}.table th{font-size:11px;color:var(--muted);text-transform:uppercase}',
  '.status{display:inline-block;padding:3px 7px;border:1px solid var(--line);border-radius:999px;font-size:11px}.ok{color:var(--green);border-color:#335d4b}.warn{color:var(--gold);border-color:#5a4d2f}.bad{color:var(--red);border-color:#66383b}',
  '.cards{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px}.card{padding:17px}.card h3{font-size:18px;margin:0}.muted{color:var(--muted)}.chips{display:flex;gap:5px;flex-wrap:wrap;margin:9px 0}.chip{padding:3px 7px;border-radius:999px;background:var(--panel2);border:1px solid var(--line);font-size:11px}',
  '.evidence{margin-top:10px;padding-top:10px;border-top:1px solid var(--line)}.ev{padding:6px 0}.spin{display:inline-block;width:13px;height:13px;border:2px solid #ffffff55;border-top-color:white;border-radius:50%;animation:s .8s linear infinite;vertical-align:-2px;margin-right:7px}@keyframes s{to{transform:rotate(360deg)}}',
  '@media(max-width:900px){.top{display:block}.controls{margin-top:14px}.grid{grid-template-columns:repeat(2,1fr)}.cards{grid-template-columns:1fr}}'
].join('');

const CLIENT = [
  "const q=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>\\\"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\\\"':'&quot;',\\\"'\\\":'&#39;'}[m]));",
  "function badge(v){const x=String(v||'—'),c=['ok','complete','CONFIRMING'].includes(x)?'ok':(x==='failed'?'bad':'warn');return '<span class=\\\"status '+c+'\\\">'+esc(x)+'</span>'}",
  "function render(d){q('#st').innerHTML=badge(d.status);q('#ok').textContent=d.summary.ok_sources;q('#raw').textContent=d.summary.raw_records;q('#cand').textContent=d.candidates.length;",
  "q('#collectors').innerHTML=d.collectors.map(r=>'<tr><td>'+esc(r.display_name)+'</td><td>'+esc(r.market)+'</td><td>'+badge(r.status)+'</td><td>'+r.records+'</td><td class=\\\"muted\\\">'+r.elapsed_ms+' ms'+(r.error?' · '+esc(r.error):'')+'</td></tr>').join('');",
  "q('#cards').innerHTML=d.candidates.map(c=>{const ev=c.evidence.slice(0,10).map(e=>'<div class=\\\"ev\\\">'+esc(e.display_name)+' · '+esc(e.market)+(e.published_at?' · '+esc(e.published_at):'')+(e.url?' · <a href=\\\"'+esc(e.url)+'\\\" target=\\\"_blank\\\" rel=\\\"noopener\\\">источник</a>':'')+'</div>').join('');return '<div class=\\\"card\\\"><div style=\\\"display:flex;justify-content:space-between;gap:8px\\\"><h3>'+esc(c.label)+'</h3>'+badge(c.state)+'</div><div class=\\\"chips\\\">'+c.sources.map(x=>'<span class=\\\"chip\\\">'+esc(x)+'</span>').join('')+'</div><div><b>Глобально:</b> '+c.sources.length+' источников · '+c.independent_lines+' независимых линий · '+esc(c.markets.join(', '))+'</div><div style=\\\"margin-top:7px\\\"><b>Целевой рынок '+esc(c.target_geo)+':</b> '+(c.target_observed?'<span class=\\\"status ok\\\">наблюдается</span>':'<span class=\\\"status warn\\\">не наблюдается</span>')+'</div><div class=\\\"evidence\\\"><b>Evidence</b>'+ev+'</div></div>'}).join('')||'<div class=\\\"muted\\\">По текущему live-срезу watchlist не дал кандидатов. Это допустимый результат.</div>'}",
  "async function run(){const b=q('#run');b.disabled=true;b.innerHTML='<span class=\\\"spin\\\"></span>Собираю…';q('#msg').innerHTML='';try{const r=await fetch('/api/run',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({target_geo:q('#market').value})}),d=await r.json();if(!r.ok)throw new Error(d.error||('HTTP '+r.status));localStorage.setItem('fashion-radar-last',JSON.stringify(d));render(d);q('#msg').innerHTML='<div class=\\\"panel\\\"><b>Последний запуск:</b> '+esc(d.generated_at)+' · рынок '+esc(d.target_geo)+'</div>'}catch(e){q('#msg').innerHTML='<div class=\\\"notice error\\\"><b>Ошибка:</b> '+esc(e.message)+'</div>'}finally{b.disabled=false;b.textContent='Запустить live-сбор'}}",
  "q('#run').onclick=run;try{const d=JSON.parse(localStorage.getItem('fashion-radar-last')||'null');if(d){q('#market').value=d.target_geo||'RU';render(d)}}catch(e){}"
].join('');

export const HTML = '<!doctype html><html lang="ru"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow,noarchive"><title>Fashion Radar</title><style>' + CSS + '</style></head><body>' +
  '<div class="wrap"><div class="top"><div class="brand"><h1>Fashion Radar</h1><p>Живой тестовый контур · глобальные сигналы отдельно от целевого рынка</p></div>' +
  '<div class="controls"><select id="market" class="market"><option>RU</option><option>US</option><option>GB</option><option>DE</option><option>FR</option><option>AE</option><option>TR</option><option>BR</option></select><button id="run" class="btn">Запустить live-сбор</button></div></div>' +
  '<div class="notice">Наблюдательный режим: без выдуманного Trend Score, вероятности, фиксированного лага и команды «закупать».</div><div id="msg"></div>' +
  '<div class="grid"><div class="stat"><div class="k">Статус</div><div id="st" class="v">—</div></div><div class="stat"><div class="k">Источников OK</div><div id="ok" class="v">—</div></div><div class="stat"><div class="k">Записей</div><div id="raw" class="v">—</div></div><div class="stat"><div class="k">Кандидатов</div><div id="cand" class="v">—</div></div></div>' +
  '<div class="panel"><h2>Источники последнего запуска</h2><div style="overflow:auto"><table class="table"><thead><tr><th>Источник</th><th>Рынок</th><th>Статус</th><th>Записей</th><th>Время</th></tr></thead><tbody id="collectors"><tr><td colspan="5" class="muted">Нажмите «Запустить live-сбор»</td></tr></tbody></table></div></div>' +
  '<div class="panel"><h2>Тренды / кандидаты</h2><div id="cards" class="cards"><div class="muted">Пока нет запуска.</div></div></div></div><script>' + CLIENT + '</script></body></html>';
